// ⚠️  DO NOT run `npm run build:app` in production.
// The main app bundle is generated by scripts/bundle_js.py (static/js/*.js → static/app.js).
// This Vite config is ONLY for development/testing of the TypeScript migration.
// Output goes to static/dist-app/app.vite.js to avoid overwriting static/app.js.
import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, 'src/app/index.ts'),
      name: 'SalmAlmApp',
      formats: ['iife'],
      fileName: () => 'app.vite.js',
    },
    outDir: resolve(__dirname, '../dist-app'),
    emptyOutDir: false,
    minify: false,
  },
});
